import {
  TOOL_CALL_LIST_DIRECTORY,
  TOOL_CALL_READ_FILE,
  TOOL_CALL_READ_FILE_FULL,
  TOOL_CALL_READ_FILES,
  TOOL_CALL_SEARCH_FILES,
  TOOL_CALL_GREP_FILES,
  TOOL_CALL_ATTACH_FILE,
  TOOL_CALL_WEB_SEARCH,
  TOOL_CALL_CREATE_FILE,
  TOOL_CALL_RENAME_FILE,
  TOOL_CALL_MOVE_FILE,
  TOOL_CALL_CREATE_DIRECTORY,
  TOOL_CALL_DELETE_FILE,
  TOOL_CALL_BATCH_RENAME,
} from './tool-format';

export interface AgentSkill {
  id: string;
  title: string;
  description: string;
  toolNames: string[];
  systemPromptFragment: string;
  systemPromptFragmentEn?: string;
}

export const allSkills: AgentSkill[] = [
  {
    id: 'web_search',
    title: '联网搜索',
    description: '在需要事实核验、最新资讯或引用来源时使用；通过结构化 TOOL_CALL 发起检索。',
    toolNames: ['web_search'],
    systemPromptFragment: [
      '[联网搜索] 仅在真正需要证据或核对时效时触发。必须使用下方括号格式（一行内）：',
      TOOL_CALL_WEB_SEARCH,
      '⚠️ 上面这行是你真正需要搜索时才输出的执行指令。绝不要把它当作示例展示给用户。输出 = 宿主立即执行。',
      '发出后勿编造检索结果；等待宿主在对话中追加 [TOOL_RESULT: web_search] 后再继续。',
    ].join('\n'),
    systemPromptFragmentEn: [
      '[Web Search] Trigger ONLY when you genuinely need evidence or need to verify timeliness. Use the bracket format below (single line):',
      TOOL_CALL_WEB_SEARCH,
      '⚠️ The line above is a live execution command you output ONLY when you actually need to search. NEVER output it as an example. Output = Host executes immediately.',
      'Do not fabricate search results; wait for the host to append [TOOL_RESULT: web_search] in the conversation before proceeding.',
    ].join('\n'),
  },
  {
    id: 'local_workspace',
    title: '本地工作区',
    description: '浏览、搜索和读取用户本地工作区的文件内容；批量读取减少对话轮次。',
    toolNames: ['list_directory', 'read_file', 'read_files', 'search_files', 'grep_files', 'attach_file_to_chat', 'create_file', 'rename_file', 'move_file', 'delete_file', 'create_directory', 'batch_rename'],
    systemPromptFragment: [
      '[本地工作区] 你可以访问用户授权的本地工作区文件夹。可用工具：',
      '',
      '1. 列出目录（类似 ls / tree）：',
      TOOL_CALL_LIST_DIRECTORY,
      '   参数说明：path=目录相对路径（默认"."根目录），recursive=是否递归（默认false），maxDepth=最大深度（默认2）',
      '',
      '2. 读取单个文件（类似 cat）：',
      TOOL_CALL_READ_FILE_FULL,
      '',
      '3. 批量读取多个文件（⚡推荐！一次性读取所有需要的文件，减少对话轮次）：',
      TOOL_CALL_READ_FILES,
      '',
      '4. 按名称搜索文件（支持智能模式 + glob 模式）：',
      TOOL_CALL_SEARCH_FILES,
      '   • 不含 * ? 等 glob 元字符时进入智能模式：按空格拆分关键词（AND），自动忽略大小写和连字符/下划线',
      '   • 含 * ? 等元字符时进入 glob 模式，支持跨目录（如 src/**/*.ts）',
      '',
      '5. 在文件内容中搜索文本/正则（类似 grep -r）：',
      TOOL_CALL_GREP_FILES,
      '   includePattern 按文件名过滤（如 *.ts），contextLines 控制上下文行数，isRegex=true 启用正则',
      '',
      '6. 读取文件指定行范围（大文件利器）：',
      TOOL_CALL_READ_FILE,
      '   省略 startLine/endLine 则读取全文：',
      TOOL_CALL_READ_FILE_FULL,
      '',
      '7. 将任意文件附加到 AI 聊天输入框（图片/PDF/文档/视频等均支持）：',
      TOOL_CALL_ATTACH_FILE,
      '   可选参数 targetSelector 用于覆盖输入框选择器',
      '   ℹ read_file 不能读取二进制文件，应改用此工具让 AI 直接看到文件内容',
      '',
      '8. 创建新文件（⚠️ 禁止覆盖已有文件，需用户批准）：',
      TOOL_CALL_CREATE_FILE,
      '   创建一个全新的文件并写入完整内容。文件已存在时会被拒绝。执行前会弹出用户审批弹窗。',
      '',
      '9. 重命名文件（在同目录内改名，需用户批准）：',
      TOOL_CALL_RENAME_FILE,
      '   newName 只能是文件名，不能包含路径。若需跨目录，请改用 move_file。',
      '',
      '10. 移动文件（可跨目录，可同时改名，需用户批准）：',
      TOOL_CALL_MOVE_FILE,
      '    srcPath=源路径，destPath=目标路径（含新文件名）。',
      '',
      '11. 创建文件夹（自动创建中间目录，需用户批准）：',
      TOOL_CALL_CREATE_DIRECTORY,
      '',
      '12. 删除文件（不可恢复！需用户批准）：',
      TOOL_CALL_DELETE_FILE,
      '',
      '13. 批量重命名/移动文件（需用户一次批准所有操作）：',
      TOOL_CALL_BATCH_RENAME,
      '',
      '⚠️ 上面的每个 [TOOL_CALL: ...] 行都是实时执行指令。你输出它 = 宿主立刻执行。绝不要把它们当作示例或说明展示。',
      '❌ 不支持 edit_file（禁止修改已有文件内容）。需要更新文件时，请先读取旧内容，再用 create_file 以新内容创建同名文件（注意：原文件必须先被删除或重命名）。',
      '',
      '[重要策略]：',
      '- 先用 list_directory 了解项目结构',
      '- 然后用 read_files 一次性批量读取所有需要的文件（推荐！）',
      '- 所有写操作（create_file/rename_file/move_file/delete_file/create_directory/batch_rename）都需要用户在弹窗中批准后才真正执行',
      '- 路径必须为工作区内的相对路径，禁止使用 ..',
      '- 发出后勿编造文件内容；等待宿主在对话中追加 [TOOL_RESULT: ...] 后再继续',
    ].join('\n'),
    systemPromptFragmentEn: [
      '[Local Workspace File Access] You can access files in the user\'s authorized local workspace. Available tools:',
      '',
      '1. List directory contents (like ls / tree):',
      TOOL_CALL_LIST_DIRECTORY,
      '   Args: path=relative dir path (default "."), recursive=bool (default false), maxDepth=int (default 2)',
      '',
      '2. Read a single file (like cat):',
      TOOL_CALL_READ_FILE_FULL,
      '',
      '3. Batch read multiple files (⚡RECOMMENDED! Read all needed files at once to minimize turns):',
      TOOL_CALL_READ_FILES,
      '',
      '4. Search files by name (smart mode + glob mode):',
      TOOL_CALL_SEARCH_FILES,
      '   • Without glob chars (* ?): smart mode — splits query by spaces (AND), case-insensitive, ignores separators',
      '   • With glob chars: glob mode — supports wildcards and cross-directory patterns (e.g. src/**/*.ts)',
      '',
      '5. Search file contents by text or regex (like grep -r):',
      TOOL_CALL_GREP_FILES,
      '   includePattern filters by filename (e.g. *.ts), contextLines shows surrounding lines, isRegex=true enables regex',
      '',
      '6. Read specific line range of a file (great for large files):',
      TOOL_CALL_READ_FILE,
      '   Omit startLine/endLine to read the entire file:',
      TOOL_CALL_READ_FILE_FULL,
      '',
      '7. Attach any file to the AI chat input (images, PDF, documents, video, etc.):',
      TOOL_CALL_ATTACH_FILE,
      '   Optional targetSelector overrides the default input field detection',
      '   ℹ read_file cannot read binary files; use this tool to let the AI see file content directly',
      '',
      '8. Create a NEW file (⚠️ cannot overwrite existing files — requires user approval):',
      TOOL_CALL_CREATE_FILE,
      '   Creates a brand-new file. Rejected if the file already exists. A user approval dialog will appear.',
      '',
      '9. Rename a file in the same directory (requires user approval):',
      TOOL_CALL_RENAME_FILE,
      '   newName must be a filename only (no path separators). Use move_file to change directories.',
      '',
      '10. Move a file (cross-directory, can rename simultaneously — requires user approval):',
      TOOL_CALL_MOVE_FILE,
      '    srcPath=source path, destPath=destination path (including new filename).',
      '',
      '11. Create a directory (auto-creates intermediate dirs — requires user approval):',
      TOOL_CALL_CREATE_DIRECTORY,
      '',
      '12. Delete a file (irreversible! requires user approval):',
      TOOL_CALL_DELETE_FILE,
      '',
      '13. Batch rename/move files (requires user approval for all operations at once):',
      TOOL_CALL_BATCH_RENAME,
      '',
      '⚠️ Every [TOOL_CALL: ...] line above is a live execution command. Output = Host executes immediately. NEVER output these as examples or illustrations.',
      '❌ edit_file is NOT supported (modifying existing file content is disabled). To update a file, read its current content, then use create_file with new content (note: the original file must be deleted or renamed first).',
      '',
      '[Key Strategy]:',
      '- First, use list_directory to understand the project structure',
      '- Then use read_files to batch-read ALL needed files at once (recommended!)',
      '- All write operations (create_file/rename_file/move_file/delete_file/create_directory/batch_rename) require user approval in a popup before executing',
      '- Paths must be relative within the workspace; ".." is forbidden',
      '- Do not fabricate file contents; wait for [TOOL_RESULT: ...] before proceeding',
    ].join('\n'),
  },
];

export function buildToolsSystemPrompt(skills: AgentSkill[], lang: 'zh' | 'en' = 'zh'): string {
  return skills
    .map((s) => (lang === 'en' && s.systemPromptFragmentEn ? s.systemPromptFragmentEn : s.systemPromptFragment).trim())
    .filter(Boolean)
    .join('\n\n');
}
